[package]
name = "yaufs-common"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", rev = "db4ac267c2e40f84377d95be242a3a55094e7ecf" }
tokio = { version = "1.24.1", features = ["rt"] }
tower-http = { version = "0.3.5", features = ["trace"] }
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-tokio"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

version-compare = "0.1.1"
opentelemetry-http = "0.7.0"
tracing = "0.1.37"
tonic = "0.8.3"
tonic-health = "0.8.0"
opentelemetry = "0.18.0"
tracing-opentelemetry = "0.18.0"
prost = "0.11.6"

[build-dependencies]
tonic-build = "0.8.4"
