[package]
name = "yaufs-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.24.1", features = ["rt"] }
tower-http = { version = "0.3.5", features = ["trace"] }
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-tokio"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

tracing = "0.1.37"
nanoid = "0.4.0"
tonic = "0.8.3"
tonic-health = "0.8.0"
opentelemetry = "0.18.0"
tracing-opentelemetry = "0.18.0"
