{
 "title": "ApacheAPISIX",
 "description": "MicroServiceAPIGatewayApacheAPISIX",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(apisix_http_status,service)"
   },
   {
    "name": "route",
    "query": "label_values(apisix_http_status,route)"
   },
   {
    "name": "instance",
    "query": "label_values(apisix_http_status,instance)"
   },
   {
    "name": "consumer",
    "query": "label_values(apisix_http_status,consumer)"
   },
   {
    "name": "node",
    "query": "label_values(apisix_http_status,node)"
   }
  ]
 },
 "panels": [
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TotalRequests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apisix_http_requests_total{instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "AcceptedConnections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=\"accepted\",instance=~\"$instance\"})",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "HandledConnections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=\"handled\",instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Nginxconnectionstate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=~\"active|reading|writing|waiting\",instance=~\"$instance\"})by(state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "TotalBandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_bandwidth{instance=~\"$instance\"}[30s]))by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Ingressperservice/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apisix_bandwidth{type=\"ingress\",service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]))by(service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(irate(apisix_bandwidth{type=\"ingress\",service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]))by(route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Egressperservice/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_bandwidth{type=\"egress\",service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]))by(service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(apisix_bandwidth{type=\"egress\",service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]))by(route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Requestspersecond(RPS)bystatuscode",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]))by(code)",
     "legendFormat": "HTTPStatus:{{code}}"
    }
   ]
  },
  {
   "title": "Requestspersecond(RPS)perservice/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]))by(service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(apisix_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m]))by(route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "RequestLatency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[1m]))by(le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[1m]))by(le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(apisix_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[1m]))by(le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "APISIXLatency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[1m]))by(le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[1m]))by(le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(apisix_http_latency_bucket{type=~\"apisix\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[1m]))by(le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "UpstreamLatency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[1m]))by(le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[1m]))by(le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(apisix_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\"}[1m]))by(le))",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Etcdmodifyindexes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apisix_etcd_modify_indexes{key=~\"consumers|global_rules|max_modify_index|prev_index|protos|routes|services|ssls|stream_routes|upstreams|x_etcd_index\"})by(key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Etcdreachable",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(apisix_etcd_reachable{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Nginxmetricerrors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(apisix_nginx_metric_errors_total{instance=~\"$instance\"})"
    }
   ]
  }
 ]
}