apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    k8s.apisix.apache.org/upstream-scheme: https
    k8s.apisix.apache.org/http-to-https: "true"
    k8s.apisix.apache.org/plugin-config-name: "oidc-admin"
  name: consul
  namespace: consul
spec:
  ingressClassName: apisix
  rules:
    - host: consul.dev.localhost
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: consul-server
                port:
                  number: 8501
          - path: /ui
            pathType: Prefix
            backend:
              service:
                name: consul-ui
                port:
                  number: 443
