apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.templates.name }}
  labels:
    app: {{ .Values.templates.name }}
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: {{ .Values.templates.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.templates.name }}
    spec:
      serviceAccountName: {{ .Values.templates.serviceAccount.name }}
      containers:
        - image: {{ .Values.templates.image }}
          name: template-service
          env:
            - name: SURREALDB_ENDPOINT
              value: "{{ .Values.templates.surrealdb.service.name }}.template-service.svc.cluster.local:{{.Values.templates.surrealdb.service.targetPort}}"
            - name: RUST_LOG
              value: {{ .Values.templates.logLevel }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            grpc:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            grpc:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      initContainers:
        - name: init-surrealdb
          image: busybox:1.28
          command: [ 'sh', '-c', "until nslookup {{ .Values.templates.surrealdb.service.name }}.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for surrealdb; sleep 2; done; sleep 30" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.templates.surrealdb.name }}
  labels:
    app: {{ .Values.templates.surrealdb.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.templates.surrealdb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.templates.surrealdb.name }}
    spec:
      serviceAccountName: {{ .Values.templates.serviceAccount.name }}
      containers:
        - image: {{ .Values.templates.surrealdb.image }}
          name: surrealdb
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          command: [ "/surreal" ]
          args: [ "start", "--user", "root", "--pass", "root" ]
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.templates.service.name }}
spec:
  ports:
    - name: {{ .Values.templates.name }}
      targetPort: {{ .Values.templates.service.targetPort }}
      port: 8000
      protocol: TCP
  selector:
    app: {{ .Values.templates.name }}
  type: {{ .Values.templates.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.templates.surrealdb.service.name }}
spec:
  ports:
    - name: "surrealdb"
      targetPort: {{ .Values.templates.surrealdb.service.targetPort }}
      port: 8000
      protocol: TCP
  selector:
    app: {{ .Values.templates.surrealdb.name }}
  type: {{ .Values.templates.surrealdb.service.type }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.templates.serviceAccount.name }}
