apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
    - name: {{ .Values.name }}
      targetPort: 8000
      port: 8000
      protocol: TCP
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: surrealdb
spec:
  ports:
    - name: "surrealdb"
      targetPort: 8000
      port: 8000
      protocol: TCP
  selector:
    app: {{ .Values.surrealdb.name }}
  type: {{ .Values.surrealdb.service.type }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: template-service