apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    {{- range $key, $value := $.Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        linkerd.io/inject: "enabled"
        {{- range $key, $value := $.Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      serviceAccountName: template-service
      containers:
        - image: {{ .Values.image }}
          name: template-service
          env:
            - name: SURREALDB_ENDPOINT
              value: "surrealdb.template-service.svc.cluster.local:8000"
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: SURREALDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: surrealdb-credentials
                  key: username
            - name: SURREALDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: surrealdb-credentials
                  key: password
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            grpc:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            grpc:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      initContainers:
        - name: init-surrealdb
          image: busybox:1.28
          command: [ 'sh', '-c', "until nslookup surrealdb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for surrealdb; sleep 2; done; sleep 30" ]
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-template"
