apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: yaufs
automountServiceAccountToken: true

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: yaufs
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: auth-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-service
  name: auth-service
  namespace: yaufs
spec:
  replicas: 1
  selector:
    matchLabels:
       app: auth-service
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
      labels:
        app: auth-service