apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instances.yaufs.io
spec:
  group: yaufs.io
  names:
    kind: Instance
    plural: instances
    singular: instance
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                imagePullSecret:
                  type: string
                replicas:
                  type: integer
                id:
                  type: string
              required:
                - image
                - replicas
                - id
