apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templates.yaufs.io
spec:
  group: yaufs.io
  names:
    kind: Template
    plural: templates
    singular: template
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                id:
                  type: string
              required:
                - image
